### ISSUE TITLE
Readme clean up

### ISSUE THREAD

**Issue by wbalmer** [wbalmer/backtracks#22]
The readme could use a bit of clean up and nicer presentation. Maybe with some friendly space emojis, better formatting, and some headers.

**Comment by gotten** [comment]
With the new content of ./tests/ we might need to change the test instructions to:
```
cd ./tests/
pytest -vvs
```
or something similar. I'm not too familiar with pytest. This seems to mix the python output with the test results but it allows you to track the fitting step.

**Comment by tomasstolker** [comment]
`pytest` can be used to make sure that nothing breaks in the code. Whenever a PR is now created, it will run the tests now with the Actions workflow. This can also be executed just as `pytest` from the main folder or indeed from within the `tests` folder. We can add more specific tests there to check e.g. specific values or if a plot file is created.

As a tutorial for user, I would recommend using `sphinx` and creating a page on e.g. [readthedocs](https://readthedocs.com). There we could also include a notebook with the example of HD 131399, installation instructions, etc. I can help set it up if you wish, but @wbalmer would need to create the page on readthedocs.

**Comment by gotten** [comment]
OK, thank you for the explanation. I'm learning something new every day with this repo :)

**Comment by wbalmer** [comment]
I can try to learn how to set this up with readthedocs, I do not know `sphinx` but am happy to learn

**Comment by wbalmer** [comment]
I cleaned up the readme in commit [c8d5206](https://github.com/wbalmer/backtracks/commit/c8d520601794959ab66337f8345d446018fb9d4d). Our badges look nice and I learned to use rst vs markdown :)
