### ISSUE TITLE
Actually document in the docstrings

### ISSUE THREAD

**Issue by wbalmer** [wbalmer/backtracks#41]
lol

**Comment by gotten** [comment]
If we have a working example for one function we can split the work and chip away at the rest.

**Comment by wbalmer** [comment]
Sounds like a plan! I'll start on this next week.

**Comment by gotten** [comment]
There might have been an error in pol2car until I noticed it while writing docstrings: https://github.com/gotten/backtracks/commit/80cd611745f2c26487582395fb5d82c87854a3cf

Can you comment on this @wbalmer? Probably had the biggest impact for GRAVITY errors that can have a big ratio between axes.

**Comment by wbalmer** [comment]
Ah, looks like that is an error, yes, the order should be x1, x2, x1_err, x2_err. could  have affected some of our gravity runs slightly. we can merge that asap and push that and our recent changes to pypi early next week.

**Comment by wbalmer** [comment]
I'll close this for now since each function has a docstring! We will continue to revise and improve them for clarity as we update the package.
