### ISSUE TITLE
Separate RV prior from other host star priors

### ISSUE THREAD

**Issue by gotten** [wbalmer/backtracks#42]
Split the 6D host star prior into 5D + 1x RV prior so we can give the users the option to override it.

See some discussion in #37.

**Comment by wbalmer** [comment]
Perhaps a kwarg override (if the user has, e.g. ground based high resolution spectroscopy they'd like to implement) for a normally distributed prior, and then a try, except KeyError -> uniform prior, to catch cases where there is no Gaia measurement? I think those would be the two cases where a user would want to override the Gaia measurement somehow.
