### ISSUE TITLE
Update sphinx documentation

### ISSUE THREAD

**Issue by wbalmer** [wbalmer/backtracks#44]
Related to #41 , create API documentation interpret able by sphinx, spruce up the home page, and add visuals to the tutorial notebook.

**Comment by tomasstolker** [comment]
You can add `pydata-sphinx-theme` to docs/requirements.txt and adjust `html_theme` in docs/conf.py.

**Comment by wbalmer** [comment]
We added integration between our docstrings, updated the theme, added a logo, so I'll close this. backtracks looks very sharp now!
