### ISSUE TITLE
Dark/light mode for logo

### ISSUE THREAD

**Issue by tomasstolker** [wbalmer/backtracks#53]
Nice logo you made @wbalmer! I am guessing you use dark mode? Because I only see the planet 😄.

From what I quickly read, this should help to add both a dark and light mode version:
https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax#specifying-the-theme-an-image-is-shown-to

**Comment by wbalmer** [comment]
Ah! I did this for the readthedocs, but not for the README.rst 

I also realize that with the images in _static, they don't appear on, e.g. pypi. so I should probably change it to still host hte images within _static, but have the link be the full url to the github file.

thanks Tomas!
